#!/bin/bash
# Regenerates released-sites.sha256: the hash of every nginx site config shipped in
# any release tag (data/conf/nginx/sites-available/ before 2.4, nginx/sites/ since),
# as render-sites.sh computes it. render-sites.sh uses the list to tell an unedited
# config of an older release from a user's edit.
#
# Run it after tagging a release (needs all tags: git fetch --tags), and commit the
# result. --check only reports whether the committed list is up to date.
set -euo pipefail

dir=$(cd "$(dirname "$0")" && pwd)
# shellcheck source=render-sites.sh
. "$dir/render-sites.sh" --lib
list="$dir/released-sites.sha256"

cd "$(git -C "$dir" rev-parse --show-toplevel)"
generate() {
    echo "# <sha256> <site> <tags>. Generated by update-released-sites.sh; do not edit."
    local tag path file
    for tag in $(git tag --sort=creatordate); do
        for path in data/conf/nginx/sites-available nginx/sites; do
            git ls-tree --name-only "$tag" "$path/" | grep '\.conf$' || true
        done | while read -r file; do
            printf '%s %s %s\n' "$(git show "$tag:$file" | site_hash mirror.intra)" "$(basename "$file")" "$tag"
        done
    done | awk '
        { key = $1 " " $2 }
        !(key in tags) { order[++n] = key; tags[key] = $3; next }
        { tags[key] = tags[key] "," $3 }
        END { for (i = 1; i <= n; i++) print order[i], tags[order[i]] }'
}

if [ "${1:-}" = --check ]; then
    if generate | cmp -s - "$list"; then
        echo "released-sites.sha256 is up to date."
    else
        echo "released-sites.sha256 is out of date; run nginx/sites-setup/update-released-sites.sh" >&2
        exit 1
    fi
else
    generate > "$list"
    echo "Wrote $list ($(grep -vc '^#' "$list") configs)."
fi
